# .travis.yml
language: node_js
node_js:
  - '9.2.1'
git:
  depth: 1
script:
  - npm run travis
notifications:
  email: false
deploy:
  - provider: npm
    email: ${NPM_EMAIL}
    api_key: ${NPM_TOKEN}
    on:
      tags: true
      branch: master
