# .travis.yml
language: node_js
node_js:
  - '12.6.0'
git:
  depth: 1
script:
  - npm run travis
notifications:
  email: false
deploy:
  - provider: npm
    email: ${NPM_EMAIL}
    api_key: ${NPM_TOKEN}
    skip_cleanup: true
    on:
      tags: true
      branch: master
